title: "Bhimani Blog"
email: adnanbhimani@gmail.com
timezone: UTC
baseurl: ''
permalink: "/:title/"
logo: 'assets/images/davis5.jpg'
favicon: 'assets/images/davis5.jpg'
author: Adnan Bhimani
paginate: 30
disqus: ''
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  adnanbhimani:
    name: Adnan Bhimani
    display_name: Adnan Bhimani
    avatar: 'assets/images/sal.png'
    email: Adnan Bhimani
    web: 
    twitter: 
    description: "Welcome to the Bhimani Blog where you are getting IT and Software development updates"

# Social
social:
  #instagram: 
  #facebook: 
  #twitter: 
  Linkedin: https://www.linkedin.com/in/adnan-bhimani-18267612a/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
